In [19]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers
from sklearn.metrics import accuracy_score, mean_squared_error
from math import sqrt
from keras.utils import to_categorical
import pandas as pd
from PIL import Image
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.metrics import mean_squared_error, r2_score
from keras.optimizers import Adam
from sklearn.metrics import mean_absolute_error
import numpy as np


In [8]:
import os

train_folder = "C:/AI PROJECT 2/Dataset/boneage-training-dataset"
test_folder = "C:/AI PROJECT 2/Dataset/boneage-test-dataset-raw"

# Count the number of folders in the train and test directories
num_classes_train = len(os.listdir(train_folder))
num_classes_test = len(os.listdir(test_folder))

print("Number of classes in training data:", num_classes_train)
print("Number of classes in testing data:", num_classes_test)

# Choose the maximum number of classes between train and test data
num_classes = max(num_classes_train, num_classes_test)
print("Total number of classes:", num_classes)

Number of classes in training data: 2642
Number of classes in testing data: 1
Total number of classes: 2642


In [22]:
from keras.utils import to_categorical
import pandas as pd
from PIL import Image

# Load the metadata from the CSV file
csv_file_path = "C:/AI PROJECT 2/Dataset/boneage-training-dataset.csv"
df = pd.read_csv(csv_file_path)

# Path to the folder containing the training images
train_folder = "C:/AI PROJECT 2/Dataset/boneage-training-dataset"

# Lists to store the image data and bone age labels
x_train = []
y_train = []

# Loop through the rows in the DataFrame
for index, row in df.iterrows():
    image_id = row['id']
    image_filename = f"{image_id}.png"  # Assuming the image filename is stored as an integer 'id'
    bone_age = row['boneage']
    image_path = os.path.join(train_folder, image_filename)
    if os.path.isfile(image_path):
        try:
            # Open and preprocess the image
            img = Image.open(image_path)
            # Preprocess the image as needed (e.g., resize, normalization)
            img = np.array(img)
            img = img.astype("float32") / 255.0
            # Add the preprocessed image and bone age label to the lists
            x_train.append(img)
            y_train.append(bone_age)
        except Exception as e:
            print(f"Error processing image: {image_filename}, Error: {e}")

# Convert the lists to numpy arrays
x_train = np.array(x_train)
y_train = np.array(y_train)

print(x_train)
print(y_train)

[[[0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
  ...
  [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157 ... 0.00392157 0.00392157 0.00392157]]

 [[0.50980395 0.50980395 0.5058824  ... 0.49019608 0.49411765 0.49411765]
  [0.50980395 0.50980395 0.5058824  ... 0.49411765 0.49411765 0.49411765]
  [0.50980395 0.50980395 0.5058824  ... 0.49411765 0.49411765 0.49411765]
  ...
  [0.5058824  0.5058824  0.5058824  ... 0.12941177 0.13333334 0.13725491]
  [0.5058824  0.5058824  0.5058824  ... 0.13333334 0.13725491 0.13725491]
  [0.5058824  0.5058824  0.5058824  ... 0.13333334 0.13725491 0.14117648]]

 [[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.      

In [10]:
# from keras.models import Sequential
# from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
# from sklearn.metrics import mean_squared_error
# from keras.optimizers import Adam
# from sklearn.metrics import mean_absolute_error
# import numpy as np

# # Normalize the images to [0, 1]
# x_train = x_train.astype("float32") / 255.0

# # Reshape the data to match the CNN input shape (assuming grayscale images)
# input_shape = x_train[0].shape
# x_train = x_train.reshape(-1, *input_shape)

# # Split the data into training and validation sets
# from sklearn.model_selection import train_test_split

# x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42)

# from keras.layers import Dropout

# model = Sequential()
# model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape+(1,)))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))
# model.add(Flatten())
# model.add(Dense(128, activation='relu'))
# model.add(Dropout(0.5))
# model.add(Dense(1, activation='linear'))

# # Compile the model
# model.compile(loss='mean_squared_error', optimizer='adam')

# # Train the model with the validation data
# history = model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_val, y_val))

# # Evaluate the model on the validation data
# y_val_pred = model.predict(x_val)

# # Calculate SSR (Sum of Squared Residuals) on validation data
# ssr_val = np.sum((y_val_pred - y_val)**2)

# # Calculate MSE (Mean Squared Error) on validation data
# mse_val = mean_squared_error(y_val, y_val_pred)

# # Calculate RMSE (Root Mean Squared Error) on validation data
# rmse_val = np.sqrt(mse_val)

# # Calculate MAE (Mean Absolute Error) on validation data
# mae_val = mean_absolute_error(y_val, y_val_pred)

# # Print validation metrics
# print("Validation SSR:", ssr_val)
# print("Validation MSE:", mse_val)
# print("Validation RMSE:", rmse_val)
# print("Validation MAE:", mae_val)

In [15]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.metrics import mean_squared_error, r2_score
from keras.optimizers import Adam
from sklearn.metrics import mean_absolute_error
import numpy as np

# Normalize the images to [0, 1]
x_train = x_train.astype("float32") / 255.0

# Reshape the data to match the CNN input shape (assuming grayscale images)
input_shape = x_train[0].shape + (1,)
x_train = x_train.reshape(-1, *input_shape)

# Split the data into training and validation sets
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42)

# Build your CNN model architecture
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='linear'))  # Output layer for regression (bone age)

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model with the validation data
history = model.fit(x_train, y_train, batch_size=32, epochs=10, validation_data=(x_val, y_val))

# Predict bone age labels for the training data
y_train_pred = model.predict(x_train)

# Calculate SSR (Sum of Squared Residuals) on training data
ssr_train = np.sum((y_train_pred - y_train)**2)

# Calculate MSE (Mean Squared Error) on training data
mse_train = mean_squared_error(y_train, y_train_pred)

# Calculate RMSE (Root Mean Squared Error) on training data
rmse_train = np.sqrt(mse_train)

# Calculate R-squared on training data
r2_train = r2_score(y_train, y_train_pred)

# Evaluate the model on the validation data
y_val_pred = model.predict(x_val)

# Calculate SSR (Sum of Squared Residuals) on validation data
ssr_val = np.sum((y_val_pred - y_val)**2)

# Calculate MSE (Mean Squared Error) on validation data
mse_val = mean_squared_error(y_val, y_val_pred)

# Calculate RMSE (Root Mean Squared Error) on validation data
rmse_val = np.sqrt(mse_val)

# Calculate R-squared on validation data
r2_val = r2_score(y_val, y_val_pred)

# Print validation metrics
print("Validation SSR:", ssr_val)
print("Validation MSE:", mse_val)
print("Validation RMSE:", rmse_val)

# Print training metrics
print("Training SSR:", ssr_train)
print("Training MSE:", mse_train)
print("Training RMSE:", rmse_train)

Epoch 1/10
75/75 [==============================] - 77s 1s/step - loss: 3332.8643 - val_loss: 1754.6533
Epoch 2/10
75/75 [==============================] - 78s 1s/step - loss: 1853.3226 - val_loss: 1677.5807
Epoch 3/10
75/75 [==============================] - 78s 1s/step - loss: 1839.5667 - val_loss: 1668.9333
Epoch 4/10
75/75 [==============================] - 79s 1s/step - loss: 1825.9110 - val_loss: 1779.4580
Epoch 5/10
75/75 [==============================] - 78s 1s/step - loss: 1831.9084 - val_loss: 1670.0050
Epoch 6/10
75/75 [==============================] - 77s 1s/step - loss: 1824.3043 - val_loss: 1677.6034
Epoch 7/10
75/75 [==============================] - 80s 1s/step - loss: 1858.7322 - val_loss: 1679.5355
Epoch 8/10
75/75 [==============================] - 79s 1s/step - loss: 1822.5631 - val_loss: 1692.0867
Epoch 9/10
75/75 [==============================] - 77s 1s/step - loss: 1863.9314 - val_loss: 1707.5527
Epoch 10/10
9/9 [==============================] - 1s 125ms/step

In [23]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization, LeakyReLU, Dropout
from keras.callbacks import EarlyStopping
from sklearn.metrics import mean_squared_error, r2_score
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator

# Normalize the images to [0, 1]
x_train = x_train.astype("float32") / 255.0

# Reshape the data to match the CNN input shape (assuming grayscale images)
input_shape = x_train[0].shape + (1,)
x_train = x_train.reshape(-1, *input_shape)

# Split the data into training and validation sets
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.1, random_state=42)


# Build your CNN model architecture
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(64))  # Reduced the number of units
model.add(LeakyReLU(alpha=0.1))
model.add(Dropout(0.5))  # Adding dropout layer for regularization
model.add(Dense(1, activation='linear'))  # Output layer for regression (bone age)

# Set your desired learning rate value
learning_rate = 0.001

# Compile the model
optimizer = Adam(learning_rate=learning_rate)
model.compile(loss='mean_squared_error', optimizer=optimizer)

# Early Stopping callback
early_stopping = EarlyStopping(monitor='val_loss', patience=5, verbose=1, restore_best_weights=True)

# Data augmentation
datagen = ImageDataGenerator(rotation_range=10, width_shift_range=0.1, height_shift_range=0.1, horizontal_flip=True)
datagen.fit(x_train)

# Train the model with the augmented data
history = model.fit(datagen.flow(x_train, y_train, batch_size=32), epochs=100, validation_data=(x_val, y_val), callbacks=[early_stopping])

# Evaluate the model on the training data
y_train_pred = model.predict(x_train)

# Calculate SSR (Sum of Squared Residuals) on training data
ssr_train = np.sum((y_train_pred - y_train)**2)

# Calculate MSE (Mean Squared Error) on training data
mse_train = mean_squared_error(y_train, y_train_pred)

# Calculate RMSE (Root Mean Squared Error) on training data
rmse_train = np.sqrt(mse_train)

# Calculate R-squared on training data
r2_train = r2_score(y_train, y_train_pred)

# Evaluate the model on the validation data
y_val_pred = model.predict(x_val)

# Calculate SSR (Sum of Squared Residuals) on validation data
ssr_val = np.sum((y_val_pred - y_val)**2)

# Calculate MSE (Mean Squared Error) on validation data
mse_val = mean_squared_error(y_val, y_val_pred)

# Calculate RMSE (Root Mean Squared Error) on validation data
rmse_val = np.sqrt(mse_val)

# Calculate R-squared on validation data
r2_val = r2_score(y_val, y_val_pred)

# Print training metrics
print("Training SSR:", ssr_train)
print("Training MSE:", mse_train)
print("Training RMSE:", rmse_train)
print("Training R-squared:", r2_train)

# Print validation metrics
print("Validation SSR:", ssr_val)
print("Validation MSE:", mse_val)
print("Validation RMSE:", rmse_val)
print("Validation R-squared:", r2_val)




Epoch 1/100
75/75 [==============================] - 121s 2s/step - loss: 4181.6069 - val_loss: 5374.4131
Epoch 2/100
75/75 [==============================] - 121s 2s/step - loss: 2445.4851 - val_loss: 2054.9058
Epoch 3/100
75/75 [==============================] - 120s 2s/step - loss: 2193.4148 - val_loss: 1670.7758
Epoch 4/100
75/75 [==============================] - 114s 2s/step - loss: 2189.7090 - val_loss: 1723.9756
Epoch 5/100
31/75 [===========>..................] - ETA: 1:06 - loss: 2102.1162

KeyboardInterrupt: 